name: BuildFromTagsCI

on:
  push:
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact.
jobs:
  build:
    name: Build APK & AppBundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.5"

      - name: Setup Java
        uses: actions/checkout@v2
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > upload-keystore.jks.asc
          gpd -d --passphrase echo "${{ secrets.RELEASE_KEYSTORE_SECRET }}" --batch upload-keystore.jks.asc > upload-keystore.jks

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --verbose

      - name: Build APPBUNDLE
        run: flutter build appbundle --release

      - name: Create Github Release
        uses: flutter_test_github_ci/release-action@v2
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.RELEASES_TOKEN }}